### ISSUE TITLE
Index is not comfortable to use

### ISSUE THREAD

**Issue by XuMuK1** [m4xig1/SpExPlus_LibriSpeech#2]
https://github.com/m4xig1/SpExPlus_LibriSpeech/blob/cf4fa479d9c7b563e72a8707d68a6eba7dd516f6/datasets/libri_dataset.py#L18

It may be a good idea to consider index as a list of observations (technically list of dicts), i.e. in format like
```python
[ ... , {"ids":["352","213"],
 "mixAudioPath":"<pathToMix>",
 "referenceAudioPath":"<pathToRef>",
 "targerAudioTarger":"<pathToTarget>"
 ... <otherMetaInfo> ...
 }
``` 

This would allow swift search for meta info like speaker ids (needed for SpEx+ classification), sample rates and other stuff necessary for the solution.

**Comment by m4xig1** [comment]
reworked
