### ISSUE TITLE
Loss input

### ISSUE THREAD

**Issue by XuMuK1** [m4xig1/SpExPlus_LibriSpeech#3]
https://github.com/m4xig1/SpExPlus_LibriSpeech/blob/ad010a1b25935d8d03618f05c77f5a39ba709e94/loss/loss.py#L24

It is better to use dict for the input, in such a way you can pass the batch data in a clearer way, have an opportunity to generalize specific things and use just one argument for the loss instead of several.

**Comment by m4xig1** [comment]
reworked
